"""
ENVI-met Orchestrator Service.
Handles ENVI-met simulation execution, file generation, and process management.
"""

import subprocess
import logging
from pathlib import Path
from typing import Optional, Dict, Any
from uuid import UUID
import json
import shutil

from app.core.config import settings

logger = logging.getLogger(__name__)


class EnviMetOrchestrator:
    """
    Orchestrator for ENVI-met simulations.
    Generates input files, executes simulations, and manages output processing.
    """
    
    def __init__(self):
        self.envi_met_path = Path(settings.ENVI_MET_PATH) if settings.ENVI_MET_PATH else None
        self.license_path = Path(settings.ENVI_MET_LICENSE) if settings.ENVI_MET_LICENSE else None
        
    def check_envi_met_installation(self) -> bool:
        """
        Check if ENVI-met is properly installed and licensed.
        
        Returns:
            True if ENVI-met is available, False otherwise
        """
        if not self.envi_met_path or not self.envi_met_path.exists():
            logger.warning(f"ENVI-met path not found: {self.envi_met_path}")
            return False
        
        if self.license_path and not self.license_path.exists():
            logger.warning(f"ENVI-met license not found: {self.license_path}")
        
        # Check for ENVI-met executable
        executable = self.envi_met_path / "envi_met_core.exe" if self.envi_met_path.suffix == ".exe" else self.envi_met_path / "envi_met_core"
        
        if not executable.exists():
            logger.warning(f"ENVI-met executable not found: {executable}")
            return False
        
        logger.info("ENVI-met installation verified")
        return True
    
    def generate_input_files(
        self,
        simulation_id: UUID,
        scenario_data: Dict[str, Any],
        output_dir: Path
    ) -> Dict[str, Path]:
        """
        Generate ENVI-met input files (.inx, .simx) from scenario data.
        
        Args:
            simulation_id: Unique simulation identifier
            scenario_data: Scenario configuration (vegetation, surfaces, buildings, climate)
            output_dir: Directory to write input files
            
        Returns:
            Dictionary mapping file types to their paths
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        
        # Generate .inx file (ENVImet IndeX file)
        inx_file = output_dir / f"{simulation_id}.inx"
        self._generate_inx_file(scenario_data, inx_file)
        
        # Generate .simx file (SIMulation eXtended file)
        simx_file = output_dir / f"{simulation_id}.simx"
        self._generate_simx_file(scenario_data, simx_file)
        
        # Generate vegetation configuration file
        veg_file = output_dir / f"{simulation_id}_vegetation.txt"
        self._generate_vegetation_file(scenario_data.get("vegetation", []), veg_file)
        
        # Generate materials configuration file
        mat_file = output_dir / f"{simulation_id}_materials.txt"
        self._generate_materials_file(scenario_data.get("surfaces", {}), mat_file)
        
        logger.info(f"Generated ENVI-met input files for simulation {simulation_id}")
        
        return {
            "inx": inx_file,
            "simx": simx_file,
            "vegetation": veg_file,
            "materials": mat_file
        }
    
    def _generate_inx_file(self, scenario_data: Dict[str, Any], output_path: Path) -> None:
        """
        Generate ENVI-met .inx file from scenario data.
        This is a simplified version - actual ENVI-met format is more complex.
        """
        inx_content = f"""# ENVI-met Index File
# Generated by Gemelo Digital

[Simulation]
Name = {scenario_data.get('name', 'Simulation')}
Duration = {scenario_data.get('duration_hours', 24)}
StartTime = 00:00
StartDate = 01.01

[Climate]
ClimateFile = {scenario_data.get('climate_file', 'default.epw')}

[Grid]
NX = 50
NY = 50
NZ = 30
DX = 5.0
DY = 5.0
DZ = 2.0

[Vegetation]
File = {output_path.stem}_vegetation.txt

[Materials]
File = {output_path.stem}_materials.txt
"""
        output_path.write_text(inx_content)
    
    def _generate_simx_file(self, scenario_data: Dict[str, Any], output_path: Path) -> None:
        """
        Generate ENVI-met .simx file with extended simulation parameters.
        """
        simx_content = f"""# ENVI-met Simulation Extended File
# Generated by Gemelo Digital

[Output]
OutputInterval = 3600
OutputVariables = T, RH, Wind, PET, Rad, SurfT, Runoff

[Advanced]
TurbulenceModel = k-epsilon
RadiationModel = Full
SoilModel = 3-Layer
"""
        output_path.write_text(simx_content)
    
    def _generate_vegetation_file(self, vegetation: list, output_path: Path) -> None:
        """
        Generate vegetation configuration file.
        """
        lines = ["# Vegetation Configuration", "# ID, Type, Species, Height, CrownDiameter, LAI"]
        
        for i, veg in enumerate(vegetation, 1):
            line = f"{i}, {veg.get('type', 'tree')}, {veg.get('species', 'unknown')}, {veg.get('height', 10)}, {veg.get('crown_diameter', 5)}, {veg.get('leaf_area_index', 3)}"
            lines.append(line)
        
        output_path.write_text("\n".join(lines))
    
    def _generate_materials_file(self, surfaces: dict, output_path: Path) -> None:
        """
        Generate materials configuration file.
        """
        lines = ["# Materials Configuration", "# ID, Name, Albedo, Emissivity, Permeability"]
        
        materials = surfaces.get("materials", [])
        for i, mat in enumerate(materials, 1):
            line = f"{i}, {mat.get('name', 'default')}, {mat.get('albedo', 0.2)}, {mat.get('emissivity', 0.9)}, {mat.get('permeability', 0.1)}"
            lines.append(line)
        
        output_path.write_text("\n".join(lines))
    
    def run_simulation(
        self,
        input_dir: Path,
        output_dir: Path,
        simulation_id: UUID
    ) -> subprocess.Popen:
        """
        Execute ENVI-met simulation.
        
        Args:
            input_dir: Directory containing input files
            output_dir: Directory for output files
            simulation_id: Simulation identifier
            
        Returns:
            Subprocess object for the running simulation
        """
        if not self.check_envi_met_installation():
            raise RuntimeError("ENVI-met is not properly installed")
        
        # Prepare command
        executable = self.envi_met_path / "envi_met_core.exe" if self.envi_met_path.suffix == ".exe" else self.envi_met_path / "envi_met_core"
        
        inx_file = input_dir / f"{simulation_id}.inx"
        
        # Build command arguments
        cmd = [
            str(executable),
            "-i", str(inx_file),
            "-o", str(output_dir),
            "-l", str(self.license_path) if self.license_path else ""
        ]
        
        # Remove empty arguments
        cmd = [arg for arg in cmd if arg]
        
        logger.info(f"Starting ENVI-met simulation: {' '.join(cmd)}")
        
        # Start simulation process
        process = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )
        
        return process
    
    def monitor_simulation(self, process: subprocess.Popen) -> Dict[str, Any]:
        """
        Monitor running simulation and return status.
        
        Args:
            process: Subprocess object for the simulation
            
        Returns:
            Dictionary with status information
        """
        return_code = process.poll()
        
        if return_code is None:
            return {
                "status": "running",
                "progress": 0.0,
                "message": "Simulation in progress"
            }
        elif return_code == 0:
            return {
                "status": "completed",
                "progress": 100.0,
                "message": "Simulation completed successfully"
            }
        else:
            return {
                "status": "failed",
                "progress": 0.0,
                "message": f"Simulation failed with return code {return_code}"
            }
    
    def cancel_simulation(self, process: subprocess.Popen) -> bool:
        """
        Cancel a running simulation.
        
        Args:
            process: Subprocess object for the simulation
            
        Returns:
            True if cancellation was successful
        """
        try:
            process.terminate()
            process.wait(timeout=10)
            logger.info("Simulation cancelled successfully")
            return True
        except subprocess.TimeoutExpired:
            process.kill()
            logger.warning("Simulation forcefully killed")
            return True
        except Exception as e:
            logger.error(f"Error cancelling simulation: {e}")
            return False


# Global orchestrator instance
envi_met_orchestrator = EnviMetOrchestrator()
